# Generated by Django 3.0.5 on 2021-06-26 17:49

import django.db.models.deletion
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210626_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.TextField(verbose_name='Genre name'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='api.Categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='genres', to='api.Genres', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(verbose_name='Title name'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[api.models.validate_year], verbose_name='Release date'),
        ),
    ]
